### ISSUE TITLE
Add Support for xml 1.1 

### ISSUE THREAD

**Issue by 0xdln1** [ethicalhackingplayground/erebus#1]
Currently erebus is not supporting xml version 1.1

[ERR] xml:  unsupported version "1.1"; only version 1.0 is supported

**Comment by ethicalhackingplayground** [comment]
Thanks! for the comment. Working on a fix as we speak.

**Comment by ethicalhackingplayground** [comment]
I just had a look at the latest versions of burp 2020 and 2021 and they now use XML v1.0. So, Erebus should work with the latest versions of burp.

Thanks for the support

**Comment by ethicalhackingplayground** [comment]
Happy hacking
